package("glib_gcvt")
    set_homepage("https://github.com/zeromake/glib")
    set_description("fork glib vasnprintf impl fcvt ecvt")
    set_license("LGPLv2")
    set_urls("https://github.com/zeromake/glib/archive/refs/tags/v$(version).tar.gz")

    add_versions("0.1.2", "2fbc916d82e8306d2c07ad661fb3c5bf97ff83c95ab101b837a9ebd937d180e5")
    on_install(function (package)
        local configs = {}
        import("package.tools.xmake").install(package, configs)
    end)
    on_test(function (package)
        assert(package:has_cfuncs("_gfcvt_s", {includes = {"glib/gcvt.h"}}))
        assert(package:has_cfuncs("_gecvt_s", {includes = {"glib/gcvt.h"}}))
    end)
