package("glib_gcvt")
    set_homepage("https://github.com/zeromake/glib")
    set_description("fork glib vasnprintf impl fcvt ecvt")
    set_license("LGPLv2")
    set_urls("https://github.com/zeromake/glib/archive/refs/tags/v$(version).tar.gz")

    add_versions("0.1.3", "7731834e8ebe880aa80e65a9903a4788e86e73491f02e6db921cf8799c772e9d")
    on_install(function (package)
        local configs = {}
        import("package.tools.xmake").install(package, configs)
    end)
    on_test(function (package)
        assert(package:has_cfuncs("_gfcvt_s", {includes = {"glib/gcvt.h"}}))
        assert(package:has_cfuncs("_gecvt_s", {includes = {"glib/gcvt.h"}}))
    end)
