package("vulkan_memory_allocator")
    set_homepage("https://gpuopen.com/vulkan-memory-allocator")
    set_description("Easy to integrate Vulkan memory allocation library ")
    set_license("MIT")
    set_urls("https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/archive/refs/tags/v$(version).tar.gz")
    add_versions("3.0.1", "2a84762b2d10bf540b9dc1802a198aca8ad1f3d795a4ae144212c595696a360c")
    on_install(function (package)
        os.cp(path.join(os.scriptdir(), "port", "xmake.lua"), "xmake.lua")
        local configs = {}
        import("package.tools.xmake").install(package, configs)
    end)
